version: '3.7'
services:
    elasticsearch:
        image: elasticsearch:6.5.2
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./backups:/usr/share/elasticsearch/backups
            - ./data:/usr/share/elasticsearch/data
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml            
        container_name: elasticsearch        
        environment:
            - node.name=elasticsearch
            - discovery.type=single-node
            - cluster.name=docker-cluster
        networks:
            - bridge
    kibana:
        image: kibana:6.5.2
        ports:
            - "5601:5601"
        networks:
            - bridge
        container_name: kibana
        environment:
            - SERVER_NAME=kibana.local
            - ELASTICSEARCH_URL=http://elasticsearch:9200    
        depends_on:
            - elasticsearch
networks:
    bridge:
        driver: bridge