apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: helloworld-appsettings:dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        
        volumeMounts:
          - name: app-config-vol
            mountPath: /etc/config  
  
  # Define volume that will contain ConfigMap data
      volumes:
        - name: app-config-vol
          configMap:
            name: appsettings.json      
