apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-configuration-env
  labels:
    app: helloworld
data:
  SQLSERVER_NAME: srv_demo1
  SQLSERVER_DBNAME: db_demo
  SQLSERVER_APP_USERNAME: user_app_demo1
  SQLSERVER_ADMIN_USERNAME: user_admin_demo1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:        
      containers:
      - env:
        - name: SQLSERVER_NAME
          valueFrom:
            configMapKeyRef:
              key: SQLSERVER_NAME
              name: helloworld-configuration-env
        - name: SQLSERVER_DBNAME
          valueFrom:
              configMapKeyRef:
                key: SQLSERVER_DBNAME
                name: helloworld-configuration-env
        - name: SQLSERVER_APP_USERNAME
          valueFrom:
              configMapKeyRef:
                key: SQLSERVER_APP_USERNAME
                name: helloworld-configuration-env
        - name: SQLSERVER_ADMIN_USERNAME
          valueFrom:
              configMapKeyRef:
                key: SQLSERVER_ADMIN_USERNAME
                name: helloworld-configuration-env
        - name: SQLSERVER_APP_PASSWORD
          valueFrom:
              secretKeyRef:
                key: db-app-password
                name: db-passwords
        - name: SQLSERVER_ADMIN_PASSWORD
          valueFrom:
              secretKeyRef:
                key: db-admin-password
                name: db-passwords

        name: helloworld
        image: helloworld-secrets:dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        
        volumeMounts:
          - name: app-configuration-vol
            mountPath: /etc/configuration
          # Example only - environment vars actually used here
          - name: secrets
            mountPath: /etc/db-passwords
            readOnly: true
  
      # Define volume that will contain ConfigMap data
      volumes:
        - name: app-configuration-vol
          configMap:
            name: app-configuration
        # Example only - environment vars actually used here    
        - name:  secrets
          secret:
            secretName: db-passwords            
