version: '2'
services:

  telegraf:
    image: telegraf:1.21.1
    pid: "host"
    network_mode: "host"
    privileged: true
    user: telegraf:995
    depends_on:
      - influxdb
    restart: always
    environment:
       - interval=60s
       - flush_interval=60s
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock

  influxdb:
    image: influxdb:1.8.10
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    restart: always
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/data:/mnt/influxdb

  grafana:
    image: grafana/grafana:8.3.3
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: always
    volumes:
      - ./grafana/config.ini:/etc/grafana/config.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
